// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SaveFolderInfo } from "./SaveFolderInfo";
import type { SaveSlotInfo } from "./SaveSlotInfo";

export type SaveInstallInfo = {
  id: string;
  name: string;
  isVanilla: boolean;
  sourceName: string | null;
  modName: string | null;
  saveDir: string;
  folders: Array<SaveFolderInfo>;
  saves: Array<SaveSlotInfo>;
};
