// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SaveSlotInfo } from "./SaveSlotInfo";

export type SaveFolderInfo = {
  folderName: string;
  displayName: string;
  region: string | null;
  saves: Array<SaveSlotInfo>;
};
