// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SaveSlotInfo = {
  fileName: string;
  folderName: string;
  baseName: string;
  slotNumber: number | null;
  sizeBytes: bigint;
  modifiedTimestamp: bigint;
  milestoneName: string | null;
};
